apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: file-content
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: file-content
    creationPolicy: Owner
  data:
    - secretKey: file-content-root-username
      remoteRef:
        key: file-content
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: file-content-root-password
      remoteRef:
        key: file-content
        property: MONGO_INITDB_ROOT_PASSWORD
