{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "file-content-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "file-content-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "file-content-root-password": "AgAFHByJva9n6dPoFLmtGDrLdF5naDmh6572fux+fSlmdGFO5Xzh780p3g5xTZJ5ZBrRfa/vFJVGboKHsttgDiGRiVgUlsLjYy6jKii1/XKdcpBU4dlhshfVbKfZp+MJwR8laCCvBIUH7u/NNTX6BuyuTOnASUTQhStcnJmJv/sPBREvb7Z2KtiXKxLQn6EzCfPEfS718gtGOWJdjh2/UhNc6IkFdz1vTxMYFbFCjiXfCmpPxxHXu5OeRhuB0+3QDXjpXjJG0I7ImcEoWZ7e4MINexbawD4A6L83p5b2YHOv8lE5yU29r7UcbFmMFYA1QFJoEed95x5lyPO0MTeSeAYNAlXZ06LdBqCe1ybG51HKi5uWzXrF5nkhJLn7iTth4l2RrJ0wl4NTw/6RUTPPMIXAkqRs+0JlqZdN/FChyZdGgMQdz9fzC3oR+iogP55tkeh7y/DNCC0Y8vfJzXWQxdfJVwLsFm2bGj4ZXR4VUsmpxIwArsnZ3i7sjkTCfEAcyYGY0cpeajNRNyDHqtws8Tdh6tfG41giVqMg+qr0kRIOSRfuMXoHOvHrQ7geTIu9DtFSulfW35meCg0Mu9+L0vDzb51lZimdaxZjy9wGXO+d+wcdl6h4tx37ycTCHUpl/izTb14IJ3jP9zxT9QGa2G+gXwZv+fQGvf6WSoMc0jVV6tfAtvXRXZhO0ZGZTgQZn5T91KFxqhObJA==",
      "file-content-root-username": "AgAd5bVb0/zM+tsCJtLwo3lZHSaPmdkfMePOvWsKL3ej2jrkH0dK3HrPofOS59M3YPtkCHmDUJID4yY30KiKPtwtrsF3dKihmBg+7IMDEVq2UZCswhNlQM8aXneS/oPpayn1AQor/7fpd84taHrf1B9qnHNOS2jN9l4T4Xu4drObcWVDy9OCMfR+odNMoS+In56KZZ2c7hDZ4p+515Hwt5/CV818ce95ZgXTqFBRm+BEiT/Te3CBzjUWubvcCzS0Mw3reYzZenVIM8TxI5mhYQmqiYpEhha9VK8QEZLlm6SpYmu325355N8AjSG7h2TnAjcLixQ78v+EkzuF5T8h2fYQkZpMeP+BZcU4Wp63+adLFdp3+Qfo9KVZChiMEkW7uo9vg3VMOZo68xNoBiZ3xJC0uH0ZadrHTPoN8I2ya50IIwaQw1zaLM6rc7nyE9BVFODJBn8LIhBN44P7wQ73Xy+hqDHdvZnwRrFvkkYTHqAy/RqHAvyXk3aOZuBKg/kaLlhjTDnNLp5FVACB3NwAQqkgbbZ3ANCkvjhKnfYYwLew27q6c/SJW4PzOVxAL0CAWDF7YdiYDMyuoaAfO9a/lztPi7pRUjeUrQXbxvvv2qlH/319RT1B0Hfu4zopUWTFr1qTmj3cK5HvtHnuXKTrTz+OYo2e6L5uS0259Euc4wAmZ9PPy2pIHL2vsPgrE72NvLXNY1gnFw=="
    }
  }
}
