mongodb:
  image:
    repository: mongo
    tag: 8.0.5
  persistence:
    mountPath: /data/db
    size: 1Gi
  service:
    ports:
      mongodb: 80
  extraEnvVars:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: $(MONGODB_ROOT_USER)
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: $(MONGODB_ROOT_PASSWORD)
