apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-content-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/file-content
